### ISSUE TITLE
Support dependabot

### ISSUE THREAD

**Issue by marwin1991** [logchange/logchange#429]
Mr. @dangoslen created [tool](https://github.com/dangoslen/dependabot-changelog-helper) that runs when new PR with given label appears. 

Create together gh-action which creates logchange entry based od Dependabot PR 

CC @janhoy because you were interested

**Comment by dangoslen** [comment]
This sounds like a great extension of my existing tool to support this format.

What my tool has helped is the ability to extract the Dependabot entries and then write them back. It might be that we could extend my tool to allow for specifying via options the use of logchange yaml file. Something like

```yaml
      - uses: dangoslen/dependabot-changelog-helper@v3
        with:
          activationLabels: dependencies
          logChangeDirectory: ./changelog
```

Because the tool already supports versioning (including unreleased) I imagine it would be relatively easy to include the logchange CLI or Docker image and update my tool to run within that context by default in case that option is added 

Thoughts?
