### ISSUE TITLE
Deprecate support for changelog.labels.types.[type] config

### ISSUE THREAD

**Issue by janhoy** [logchange/logchange#541]
Today there are two ways to configure type labels. You can use

```yaml
changelog:
  labels:
    types:
      entryTypesLabels:
        security: Security
        other: Other
        removed: Removed
```

or you can do

```yaml
changelog:
  labels:
    types:
      security: Security
      other: Other
      removed: Removed
```

Since there are reserved sub keys of `types` already, the latter form should not be allowed and should be deprecated. In your own `changelog/logchange-config.yml` file and in README you have redundantly defined your labels both ways.
